- name: task level variables
  hosts: localhost
  vars:
    Course: DevOps
    Trainer: Lord Sri RadhaKrishna
    Duration: 110HRS
  tasks:
  - name: check variable
    vars:
      Course: DevOps with AWS
    ansible.builtin.debug:
     msg: "HareRama this is {{Course}}, Trainer is {{Trainer}},Duration is {{Duration}}"