- name: task level variables
  hosts: localhost
  vars:
    Course: DevOps
    Trainer: Lord Sri RadhaKrishna
    Duration: 110HRS
  tasks:
  vars:
    Course: DevOps with AWS
  - name: check variable
    ansible.builtin.debug:
     msg: "HareRama this is {{Course}}, Trainer is {{Trainer}},Duration is {{Duration}}"