- name: loops
  hosts: localhost
  become: yes
  tasks: 
  - name: print persons
    ansible.builtin.debug:
      msg: "HareKrishna persons {{item}}"
    loop:
    - Prahlada
    - Pothana
    - Bilva
    - Vidura