- name: loops
  hosts: localhost
  become: yes
  tasks: 
  - name: install some packages
    ansible.builtin.package: 
      name: "{{item}}"
      state: present
    loop:
    - git
    - postfix
    - mysql